// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAt0oD8eIf8fRKBnRPvXSP6g_h0_vqSco8',
    appId: '1:857336884255:web:dd759ad1c1dcd5a117b92a',
    messagingSenderId: '857336884255',
    projectId: 'flutter-web-330d4',
    authDomain: 'flutter-web-330d4.firebaseapp.com',
    storageBucket: 'flutter-web-330d4.firebasestorage.app',
    measurementId: 'G-3ZVGJE7CVX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpCaITj0yOMZyz9eOPTuOEJWNVGEOseUM',
    appId: '1:857336884255:android:4bf7d36e5f3c58f117b92a',
    messagingSenderId: '857336884255',
    projectId: 'flutter-web-330d4',
    storageBucket: 'flutter-web-330d4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNiiCwvO9cPvnBVDvgwL3Jj1WyaXEaHlg',
    appId: '1:857336884255:ios:9bb829b7f44aaa8117b92a',
    messagingSenderId: '857336884255',
    projectId: 'flutter-web-330d4',
    storageBucket: 'flutter-web-330d4.firebasestorage.app',
    iosBundleId: 'com.example.dioProject',
  );
}
