// ignore_for_file: constant_identifier_names

enum AssetIcons {
  avatar,
  document_management_icon,
  bank_of_america,
  capital_one,
  wells_fargo,
  citigroup,
  jpmorgan_chase,
  fund_balance_icon,
  offer,
  rent_icon,
  email_icon,
  line,
  edit,
  select_date_edit_icon,
  password_eye,
  copy_icon,
  car_icon,
  camera_icon,
  approve_tick,
  close_tick,
  exclamation_icon,
  exclamation_icon_grey,
  food,
  education,
  recreation_icon,
  live_photos,
  verified_circle,
  logout,
  square_feet,
  pool_icon,
  deals,
  min_arrow_left,
  min_arrow_right,
  play_icon,
  favorite_filled_icon,
  gas_icon,
  electricity_icon,
  storage_icon,

  pause_icon,
  help_center,
  photography_service,
  settings,
  dot,
  delete_icon,
  new_password_icon,
  download_icon,
  search_icon,
  plane,
  underground_subway_icon,
  time_schedule_icon,
  direction_icon,
  cat_icon,
  heat_icon,
  water_icon,
  tabler_alert_circle_filled,
  ac_icon,
  dollar_icon,
  elevator_icon,
  furnished_icon,
  no_smoking_icon,
  swimming_pool_icon,
  wheelchair_icon,
  down_arrow,
  bedroom_icon,
  area_icon,
  verified_shield_icon,
  star_icon,
  video,
  photos,
  virtual_tour,
  like_icon,
  share_icon,
  phone_icon,
  home_other,
  home,
  alert,
  pdf_image,
  us,
  app_logo,
  password_visibility,
  upload_icon,
  dropdown_icon,
  drop_up,
  gallery_icon,
  remove_icon,
  video_icon,
  new_message,

  authenticator_app,
  apple_icon,
  facebook_icon,
  google_icon,
  search,
  more_option_icon,
  mastercard_payment_icon,
  mail,
  messages,
  message_icon,
  menu,
  meet,

  blank,
  arrow_left,
  arrow_right,
  check_box,
  check_circle,
  cross_mark,
  check_mark,
  ArrowUpRight,
  listings,
  offers,
  inspections,
  calender_icon,
  filter_icon,
  heart_icon,
  grey_share_icon,
  red_cross_mark,
  favorite_listing_icon,
  bathroom_icon,
  gated_entry_icon,
  loft,
  fireplace_icon,
  dishwasher_icon,
  fitness_center,
  visa_payment_icon,
  dog_vector_icon;

  factory AssetIcons.fromName(String? name) => AssetIcons.values.firstWhere(
        (e) => e.name == name,
        orElse: () => AssetIcons.blank,
      );
}

enum AssetIconType {
  monotone,
  multicolor,
  ;

  static const all = values;
}

extension AssetIconsX on AssetIcons {
  static const String _basePath = 'assets/icons';

  String asset(AssetIconType type) => '$_basePath/$name.svg';
}
